const PROMPT_BANK = [
  // Workplace & Meetings
  "What your 9am meeting actually is",
  "One word for a meeting that could have been an email",
  "What 'let's circle back' really means",
  "One word for a LinkedIn post that starts with 'Humbled'",
  "What 'per my last email' really says",
  "One word for a group project where you do everything",
  "What Friday afternoon at work actually is",
  "What happens at minute 45 of a 30-minute meeting",
  "One word for the coworker who replies all",
  "What 'synergy' means in a job posting",
  "One word for your inbox on Monday morning",
  "What 'we're like a family here' means in an interview",
  "One word for a mandatory fun work event",
  "What a 'quick sync' always turns into",
  "One word for the coworker who eats lunch at their desk loudly",
  "What 'bandwidth' means when your boss says it",
  "One word for performance review season",
  "What your out-of-office reply is hiding",
  "One word for a corporate team-building exercise",
  "What 'we'll revisit compensation next quarter' means",

  // Remote Work & WFH
  "What 'working from home' looks like by 3pm",
  "One word for your WFH office setup",
  "What you're doing when you turn your camera off",
  "One word for the background you use on video calls",
  "What you wear to a video call from the waist down",
  "One word for 'I'll be right back' during a meeting",
  "What the commute is when you work from home",
  "One word for your coworker's dog on a video call",
  "What 'I have another call' really means",
  "One word for your home desk chair",

  // Sleep & Night
  "One word for checking your phone at 3am",
  "What the voice in your head at 3am sounds like",
  "One word for the thought that wakes you up at 2am",
  "What you're actually doing when you can't sleep",
  "One word for setting five alarms",
  "What snoozing your alarm three times is called",
  "One word for Sunday night when Monday looms",
  "What you tell yourself about your sleep schedule",
  "One word for the one more episode at midnight",
  "What 'just five more minutes' actually means",

  // Phones & Technology
  "What your phone battery at 8% feels like",
  "One word for the tab you've had open for three weeks",
  "What your browser history says about you",
  "One word for when autocorrect betrays you",
  "What happens when the Wi-Fi drops mid-call",
  "One word for the notification you always ignore",
  "What doom-scrolling at midnight is",
  "One word for your screen time report",
  "What your phone lock screen is covered with",
  "One word for the app you delete then redownload",
  "What you do right after saying 'I need to use my phone less'",
  "One word for your unread email count",
  "What 'I'll text you back later' means",
  "One word for the podcast you've never finished",
  "What updating your phone when you need it most is",

  // Social Media
  "One word for a story you posted then immediately deleted",
  "What your social media makes your life look like",
  "One word for someone who posts their gym selfie every day",
  "What posting a vague status and waiting for replies is",
  "One word for a Twitter/X argument at 11pm",
  "What 'I barely use social media' means",
  "One word for the photo you took but never posted",
  "What subtweeting your frustration is",
  "One word for the influencer who 'authentically' promotes everything",
  "What the comments section always becomes",
  "One word for a viral video you watched fifteen times",
  "What 'for you page' has become",
  "One word for oversharing on Instagram stories",
  "What the follower count on your personal account is",
  "One word for unfollowing someone without telling them why",

  // Food & Eating
  "What happens when you say 'I'll just have one'",
  "One word for opening the fridge a third time",
  "What the drive-thru line at 11pm is full of",
  "One word for cooking a real meal vs ordering delivery",
  "What your meal prep Sunday actually produces",
  "One word for when the food delivery is 45 minutes late",
  "What 'I'm not that hungry' means before a meal",
  "One word for the half-eaten leftovers in your fridge",
  "What brunch costs now",
  "One word for the restaurant you always go to when you can't decide",
  "What happens to your diet every weekend",
  "One word for a $7 avocado toast",
  "What your idea of cooking is on a weeknight",
  "One word for eating straight from the pot",
  "What the last thing you Uber Eats'd was",

  // Money & Cost of Living
  "What checking your bank account after a weekend is",
  "One word for rent in 2025",
  "What your grocery bill has become",
  "One word for buying something on sale you didn't need",
  "What 'treating yourself' does to your savings",
  "One word for the subscription you forgot you had",
  "What your coffee habit costs monthly",
  "One word for looking at housing prices right now",
  "What happens every time you open your banking app",
  "One word for the credit card you tell yourself is for emergencies",
  "What 'I'm saving money' looks like in practice",
  "One word for tipping culture in 2025",
  "What the cost of a night out has become",
  "One word for your streaming service count",
  "What you feel when you check your 401k",

  // Relationships & Dating
  "What running into your ex feels like",
  "One word for a first date that has no second date",
  "What 'I'm not looking for anything serious' means",
  "One word for leaving someone on read for three days",
  "What ghosting someone you liked is",
  "One word for the talking stage that never goes anywhere",
  "What 'we should hang out sometime' usually leads to",
  "One word for sending a risky text then putting your phone down",
  "What your relationship status on Instagram says",
  "One word for the person who texts at midnight but not at noon",
  "What 'I'll call you' means in 2025",
  "One word for a long relationship that just fades out",
  "What 'it's complicated' really is",
  "One word for checking their location without texting",
  "What canceling plans last minute has become",

  // Family
  "What holiday dinner conversation always turns into",
  "One word for being asked when you're getting married",
  "What your parents' tech support call is about",
  "One word for a family group chat",
  "What the question 'are you eating enough' really means",
  "One word for your childhood bedroom at your parents' house",
  "What bringing your partner home for the first time is like",
  "One word for unsolicited parenting advice",
  "What 'we need to talk' from a family member means",
  "One word for sibling arguments that never fully end",

  // Health & Fitness
  "What 'I'll start Monday' actually means",
  "One word for your posture right now",
  "What the gym membership you never use is",
  "One word for the 6am workout you scheduled for yourself",
  "What you tell yourself before skipping the gym",
  "One word for walking instead of actually running",
  "What 'I've been pretty active lately' means",
  "One word for the step count on your smartwatch today",
  "What happens on day three of a new diet",
  "One word for taking the elevator instead of the stairs",
  "What 'I'm being healthy' looks like at a restaurant",
  "One word for your water intake compared to your coffee intake",
  "What the wellness app you downloaded once is",
  "One word for stretching you keep meaning to do",
  "What signing up for a 5K in a moment of motivation becomes",

  // Shopping & Stuff
  "What happens at self-checkout every time",
  "One word for the Amazon package you forgot you ordered",
  "What your online cart looks like at 1am",
  "One word for buying something you saw in a TikTok ad",
  "What 'I needed it' means after an impulse buy",
  "One word for the thing you bought that's still in the box",
  "What Black Friday shopping does to you",
  "One word for buying the same thing twice because you lost the first one",
  "What free shipping minimum does to your cart",
  "One word for your closet right now",

  // Commuting & Travel
  "One word for your commute on a Monday",
  "What every airport security line is",
  "One word for the person reclining their seat on a plane",
  "What checking in for a flight 24 hours early is",
  "One word for the delay announcement at the gate",
  "What 'we'll be landing shortly' means when you're three hours late",
  "One word for someone talking on speaker in public",
  "What highway traffic at 5:30pm is",
  "One word for parallel parking in front of people",
  "What the person who sprints through the airport is feeling",

  // Weather & Seasons
  "One word for the first cold day of fall",
  "What summer humidity feels like",
  "One word for checking the weather app obsessively",
  "What the one nice spring day everyone loses their mind over is",
  "One word for Monday after daylight saving time",
  "What seasonal depression has become",
  "One word for the weather in April",
  "What everyone says when it gets cold and then warm again",
  "One word for the person who complains about heat then complains about cold",
  "What shoveling snow at 7am is",

  // AI & Tech Culture (2025/2026)
  "One word for an AI-generated email you can always spot",
  "What using AI to write your work emails is",
  "One word for a chatbot that confidently gives wrong answers",
  "What 'I used AI to help with this' sounds like in 2025",
  "One word for your AI assistant misunderstanding you completely",
  "What asking AI to fix your code then breaking it more is",
  "One word for a deepfake you almost believed",
  "What AI-generated art in a design deck is",
  "One word for the AI feature no one asked for in every app",
  "What 'it's just a tool' means when your job is threatened by AI",

  // Procrastination & Productivity
  "What you do instead of the thing you're supposed to do",
  "One word for reorganizing your desk instead of starting work",
  "What 'I work better under pressure' actually means",
  "One word for making a to-do list instead of doing the list",
  "What a productive Sunday plan becomes by 4pm",
  "One word for watching one more video before starting",
  "What 'I just need to get in the zone' is an excuse for",
  "One word for the task that's been on your list for a month",
  "What opening fifteen tabs to research something is",
  "One word for your idea of multitasking",

  // Social Situations
  "What showing up somewhere and not knowing anyone is",
  "One word for arriving early to a party",
  "What pretending to laugh at a joke you didn't hear is",
  "One word for someone who won't stop talking about their marathon",
  "What texting someone who's in the same room is",
  "One word for a group chat that only two people use",
  "What 'sounds good' means in a text",
  "One word for accidentally liking a photo from three years ago",
  "What everyone does at a wedding when a slow song starts",
  "One word for the person at a party who's always on their phone",
  "What 'I'm almost there' means when you haven't left yet",
  "One word for making plans you know you'll cancel",
  "What your face looks like in a group photo you didn't approve",
  "One word for holding the elevator for someone far away",
  "What every neighborhood Facebook group post is",

  // Mornings
  "One word for your mood before coffee",
  "What the first thing you check in the morning is",
  "One word for a shower that was supposed to be quick",
  "What 'I'm a morning person' means when you actually try it",
  "One word for running late but still stopping for coffee",
  "What hitting snooze for the fourth time feels like",
  "One word for making a healthy breakfast vs what actually happens",
  "What deciding what to wear takes",
  "One word for the first meeting before 9am",
  "What breakfast is when you're running late",

  // Weekend & Free Time
  "What a 'productive weekend' plan becomes",
  "One word for Sunday scaries",
  "What binge-watching a whole season in one day is",
  "One word for making plans and then wanting to cancel them",
  "What your 'me time' usually looks like",
  "One word for napping at 2pm on a Saturday",
  "What 'I'll relax this weekend' always turns into",
  "One word for the Sunday task list you wrote on Friday",
  "What staying up late because it's Friday feels like on Saturday morning",
  "One word for the hobby you said you'd finally start",

  // Miscellaneous Life
  "What the miscellaneous drawer in your house is",
  "One word for the charger you can never find",
  "What your password actually is",
  "One word for checking if you locked the door again",
  "What 'I'm not going to be on my phone tonight' lasts",
  "One word for a long line at the DMV",
  "What reading the terms and conditions is",
  "One word for the warranty card you'll never mail in",
  "What trying to cancel a subscription involves",
  "One word for the instruction manual you throw away",
  "What 'some assembly required' actually means",
  "One word for the Wi-Fi password at a new place",
  "What everyone does when a song they know comes on",
  "One word for getting into bed after a long day",
  "What your shower thoughts are actually about",
  "One word for recognizing an actor but forgetting their name",
  "What 'I'll remember it later' never does",
  "One word for arriving somewhere and forgetting why you came",
  "What the note in your phone that says 'remember this' is",
  "One word for a word you suddenly can't spell",

  // Extra Bangers
  "What 'I'm not tired' sounds like at 11pm",
  "One word for the gym in January vs February",
  "What everyone calls a text that's actually a novel",
  "One word for the person ahead of you at Starbucks with a complicated order",
  "What your Spotify Wrapped says about you",
  "One word for getting a compliment and immediately doubting it",
  "What 'I don't watch much TV' means",
  "One word for a group project meeting where nothing gets decided",
  "What looking at old photos of yourself feels like",
  "One word for a movie trailer that was better than the movie",
  "What everyone says when they hear a good deal",
  "One word for the feeling after sending an important email",
  "What the last thing you Googled was at 1am",
  "One word for your desk after a long week",
  "What 'I'll just look at the menu for a second' turns into",
  "One word for the playlist that knows you too well",
  "What your Notes app is actually for",
  "One word for crying at a commercial",
  "What every group vacation planning chat becomes",
  "One word for buying a gift card when you don't know what to get",

  // Finishing 300
  "What you do when you hear your name in a conversation across the room",
  "One word for the face you make when a photo is taken unexpectedly",
  "What 'I've been meaning to call you' really is",
  "One word for the thing you rehearse saying but never do",
  "What reading a 'final warning' bill feels like",
  "One word for the panic when you think you lost your wallet",
  "What finding $20 in an old jacket is",
  "One word for everyone's excuse to not go to the gym this week",
  "What the last thing you bought that you regretted is",
  "One word for eating something you dropped on the floor",
  "What 'I'm not a picky eater' means until it matters",
  "One word for the person who never puts their phone down at dinner",
  "What everyone does in a elevator with strangers",
  "One word for buying something nice and then being afraid to use it",
  "What a new year's resolution looks like by February",
  "One word for the email thread with 47 people on it",
  "What ignoring a bill until it goes away is called",
  "One word for your Google search history at midnight",
  "What happens when you say 'I'll just check one thing'",
  "One word for owning three different lip balms and still having chapped lips",
  "What the end of a long phone call is always followed by",
  "One word for waving back at someone who wasn't waving at you",
  "What 'I don't really care where we eat' leads to",
  "One word for the amount of tabs open on your browser right now",
  "What reading old texts from three years ago feels like",
  "One word for the look you give yourself in the mirror on a bad day",
  "What happens every time you say 'I'll just have water'",
  "One word for a birthday cake candle you can't blow out",
  "What every office kitchen passive-aggressive note is",
  "One word for the checkout line that looked shorter",
  "What 'I'm almost done' means during a video game",
  "One word for pretending to be busy when you walk past someone you know",
  "What happens when your phone rings instead of texts",
  "One word for the courage you have right before you send the text",
  "What 'we'll see' means when a parent says it",
];
